CRUD Structs
pa-fadb/backend-new pull request #5
Opened 2023-01-21 15:08 UTC by TNTzx

Adds a few CRUD controls for `musicLabel`s and `artist`s:
- Create
- Get by ID or name
- Update
- Delete

This PR also includes new `UpdateTemplate`s.

2023-01-21 16:08 UTC, naoei requested changes
I don't know if I will use most of these functions within the routers since these CRUD structs are mainly just shorthands for the longer and direct Prisma approach. It could be warranted if there were some extra logic for these.

2023-01-21 16:08 UTC, naoei commented on src/structures/artist.ts
> +            where: { name: name },
This should get from `safe_name` instead. which hasn't been implemented in the schema, so you'll have to do that as well - and by extension, generate the `safe_name` in `create()`.

Same applies to music labels.

2023-01-22 02:38 UTC, TNTzx commented
sometimes some CRUD operations could require an update (like some security vuln or extra validation / conversion on the template) and it would be bad to copy paste that update on all endpoints that need to do anything related to the operation being used

like for example the safe name part, thought that could be put in `artistCTToInput` instead

plus it's easier to put things into a function since that abstracts it so that you won't have to type out `Database.artist.create(...)`

2023-01-22 02:40 UTC, TNTzx commented on src/structures/artist.ts
> +            where: { name: name },
i'll open a new PR to include `safeName` in both `artist`s and `musicLabel`s

2023-01-22 04:37 UTC, naoei commented
I guess it's fine then.

2023-01-22 04:37 UTC, naoei approved these changes

2023-01-22 04:37 UTC, merged